# fly.toml app configuration file generated for fittrackr on 2023-10-20T14:23:58+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fittrackr"
primary_region = "otp"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
