# fly.toml app configuration file generated for fiturself on 2023-07-17T17:15:40+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fiturself"
primary_region = "ams"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
